name: on_pr_to_openjdk_images

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'openjdk/Dockerfile'

env:
  REGISTRY: ghcr.io
  FFMPEG_VERSION: "5.0.1"
  RUNTIME_IMAGE: "runtime"
  BASE_IMAGE: "base"
  BUILD_IMAGE: "build"
  JDK_PKG_URL: "https://download.java.net/java/GA/jdk18.0.1.1/65ae32619e2f40f3a9af3af1851d6e19/2/GPL/openjdk-18.0.1.1_linux-x64_bin.tar.gz"
  JDK_EA_PANAMA_PKG_URL: "https://download.java.net/java/early_access/panama/1/openjdk-19-panama+1-13_linux-x64_bin.tar.gz"
  JDK_VERSION: "18"
  JDK_EA_VERSION: "19"
  IMAGE_NAME: ${{ github.repository }}


jobs:

  pr_to_openjdk:
    environment: ghcr.io
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
        with:
          driver-opts: network=host

      - name: Pull build image
        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.FFMPEG_VERSION }}-${{ env.BUILD_IMAGE }}

      - name: Inspect build image
        id: build-image
        run: >-
          echo "::set-output name=digest::$(
            docker image inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.FFMPEG_VERSION }}-${{ env.BUILD_IMAGE }} | jq -r '.[] | .RepoDigests[]'
          )"

      - name: Pull runtime image
        run: docker pull ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.FFMPEG_VERSION }}-${{ env.RUNTIME_IMAGE }}

      - name: Inspect runtime image
        id: runtime-image
        run: >-
          echo "::set-output name=digest::$(
            docker image inspect ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.FFMPEG_VERSION }}-${{ env.RUNTIME_IMAGE }} | jq -r '.[] | .RepoDigests[]'
          )"

      - name: "ffmpeg-debian:<ffmpeg-version>-openjdk-<jdk-version> image building stage"
        id: openjdk-ga-image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: ./openjdk
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.FFMPEG_VERSION }}-openjdk-${{ env.JDK_VERSION }}
          build-args: |
            BUILD_IMAGE_DIGEST_TAG=${{ steps.build-image.outputs.digest }}
            RUNTIME_IMAGE_DIGEST_TAG=${{ steps.runtime-image.outputs.digest }}
            JDK_PKG_URL=${{ env.JDK_PKG_URL }}

      - name: "ffmpeg-debian:<ffmpeg-version>-openjdk-<jdk-version>-ea-panama image building stage"
        id: openjdk-ea-panama-image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: ./openjdk
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.FFMPEG_VERSION }}-openjdk-${{ env.JDK_EA_VERSION }}-ea-panama
          build-args: |
            BUILD_IMAGE_DIGEST_TAG=${{ steps.build-image.outputs.digest }}
            RUNTIME_IMAGE_DIGEST_TAG=${{ steps.runtime-image.outputs.digest }}
            JDK_PKG_URL=${{ env.JDK_EA_PANAMA_PKG_URL }}
