name: on_pr_to_base_image

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'base/Dockerfile'

env:
  REGISTRY: ghcr.io
  FFMPEG_VERSION: "5.0.1"
  BASE_IMAGE: "base"
  IMAGE_NAME: ${{ github.repository }}

jobs:

  pr_to_base:
    environment: ghcr.io
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf
        with:
          driver-opts: network=host

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: "ffmpeg-debian:base image building stage"
        id: base-image
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: ./base
          push: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.BASE_IMAGE }}
